### ISSUE TITLE
`.DS_store` na spada v repozitorij.

### ISSUE THREAD

**Issue by andrejbauer** [vkriznar/less-game#1]
Ta datoteka je v zvezi z MacOS in ne paše v repozitorij, prosim, da se jo pobriše povsod, kjer jo imata.
Potem naredita še `.gitignore` in vanjo dodajta ime te datoteke, da je ne bo git ponujal.

**Comment by andrejbauer** [comment]
Še malo bolj prav bi bilo, če bi omenil oba commita, ki zapirata ta issue (manjka omemba 44e131301cea0664c66e0467b59bc09b30c0c2ba). Čisto prav bi bilo pa tako, da bi bil *en sam commit*, ki zapre issue, se pravi, moral bi združiti 44e131301cea0664c66e0467b59bc09b30c0c2ba in  0f4edf8 v en commit, že ko si šel to delat.

**Comment by BumbarG** [comment]
Velja, bom ob naslednjem issue-u upošteval. Hvala za opozorilo.
